stages:
  get_data:
    cmd: python get_farmer_data.py
    deps: 
    - get_farmer_data.py
    outs: 
    - data_raw.csv
  process: 
    cmd: python process_farmer_data.py
    deps:
      - process_farmer_data.py
      - data_raw.csv
    outs: 
      - data_processed.csv
  train:
    cmd: python train_farmer.py
    deps: 
      - train_farmer.py
      - data_processed.csv
    outs:
      - by_region.png
    metrics:
      - metrics.json:
          cache: false